import { packDocument } from './common';
import { canVerifyClaim } from './debate-state';
import { safeSourceURL } from './document-state';

export const debateHtml = packDocument(`
<div><h2>Debate desk</h2><p class="muted">Bring a point of view. Follow the evidence.</p></div>
<details><summary>Add claims &amp; score</summary><div id="scorecard" class="row" aria-label="Manual scorecard"></div>
<form id="add" class="stack panel"><label>New claim<textarea id="new-claim" rows="2" required maxlength="1200" placeholder="State one checkable claim"></textarea></label><div class="row"><select id="new-side" aria-label="Claim side"><option>Affirmative</option><option>Negative</option></select><button id="add-button" type="button" class="primary">Add claim</button></div></form></details>
<section class="stack"><div class="row space"><h3>Living discussion</h3><span class="badge">Relationships, not verdicts</span></div><form id="contribute-form" class="row"><input id="contribution-text" aria-label="Your contribution" placeholder="A thought, a challenge, a question…" maxlength="1200" required class="grow"><button id="contribute-button" type="button" class="primary">Contribute</button></form><div id="contributions" class="stack" aria-label="Debate contributions"></div></section>
<div id="claims" class="stack" aria-label="Debate claims"></div>`, String.raw`
const safeSourceURL=${safeSourceURL.toString()};const canVerifyClaim=${canVerifyClaim.toString()};
const claims=document.getElementById('claims'),scorecard=document.getElementById('scorecard');
const drafts={},opened=new Set();
const contributionInput=document.getElementById('contribution-text'),contributionButton=document.getElementById('contribute-button');let submitted='';
const sendContribution=()=>{if(!contributionInput.value.trim())return;submitted=contributionInput.value;contributionButton.disabled=true;contributionButton.textContent='Connecting…';notice.textContent='';present.contribute(submitted)};contributionButton.onclick=sendContribution;contributionInput.onkeydown=event=>{if(event.key==='Enter'&&!contributionButton.disabled){event.preventDefault();sendContribution()}};
window.addEventListener('present:contribution-result',event=>{contributionButton.disabled=false;contributionButton.textContent='Contribute';if(event.detail.ok){if(contributionInput.value===submitted)contributionInput.value=''}else notice.textContent=event.detail.error||'Not saved. Try again.'});
const renderContributions=()=>{const feed=document.getElementById('contributions');feed.replaceChildren();const current=state();const items=records(current,'contribution').sort((a,b)=>Number(b.at)-Number(a.at));for(const item of items){const article=el('article',{className:'panel stack','data-contribution-id':item.id});article.append(el('p',{},item.text||''),el('small',{},(item.createdBy===actor()?'You':/^[a-f0-9-]{36}$/.test(String(item.createdBy))?'Participant':String(item.createdBy||'Participant'))+' · '+timestamp(item.at)));const links=Array.isArray(item.links)?item.links:[];for(const link of links){const claim=current['claim:'+link.claimId];const stale=!claim||claim.text!==link.claimText;article.append(el('p',{className:'muted'},(stale?'Claim changed · review link':link.relation==='support'?'Supports':link.relation==='challenge'?'Challenges':'Questions')+' · '+String(link.claimText||'')))}if(!links.length)article.append(el('small',{},'Unassigned · needs a closer look'));article.append(button('Remove contribution',()=>commit({['contribution:'+item.id]:null}),'danger'));feed.append(article)}if(!items.length)feed.append(empty('Contribute above. Your exact words stay attached to the claims they address.'))};
for(const side of ['Affirmative','Negative']){const key='score:'+side.toLowerCase(),input=el('input',{type:'number',min:0,max:100,step:1,'aria-label':side+' manual score'});input.onchange=()=>{const value=Number(input.value);if(Number.isInteger(value)&&value>=0&&value<=100)commit({[key]:value});else render()};scorecard.append(field(side+' · manual / 100',input))}
const render=()=>{renderContributions();const focus=rememberFocus(claims);const current=state();for(const side of ['Affirmative','Negative']){const input=scorecard.querySelector('[aria-label="'+side+' manual score"]');if(document.activeElement!==input)input.value=Number(current['score:'+side.toLowerCase()])||0}claims.replaceChildren();const items=records(current,'claim').sort((a,b)=>Number(a.at)-Number(b.at));for(const claim of items){const panel=el('article',{className:'panel claim','data-claim-id':claim.id});const status=['pending','verified','disputed'].includes(claim.status)?claim.status:'pending';panel.append(row(el('span',{className:'badge'},claim.side||'Affirmative'),el('span',{className:'badge'},status==='verified'?'Manually verified':status==='disputed'?'Disputed':'Pending verification')),el('p',{},claim.text||''));if(claim.quotedEvidence)panel.append(el('blockquote',{},'“'+claim.quotedEvidence+'”'));for(const raw of Array.isArray(claim.sourceURLs)?claim.sourceURLs:[]){const url=safeSourceURL(raw);if(url)panel.append(button(url,()=>present.openLink(url),'source'))}if(status==='verified')panel.append(el('small',{},'Marked verified by '+String(claim.verifiedBy||'a participant')+' · '+timestamp(claim.verifiedAt)));panel.append(choice(['pending','verified','disputed'],status,'Evidence status',value=>{const latest=state()['claim:'+claim.id];if(value==='verified'&&!canVerifyClaim(latest||{})){notice.textContent='Add an exact quote and a valid source URL before marking this claim verified. No evidence is generated automatically.';render();return}update('claim',claim.id,{status:value,verifiedBy:value==='verified'?actor():null,verifiedAt:value==='verified'?Date.now():null})}));
const details=el('details'),summary=el('summary',{},'Edit claim and evidence'),form=el('form',{className:'stack'});const text=el('textarea',{rows:2,maxlength:1200,'aria-label':'Claim text'}),quote=el('textarea',{rows:3,maxlength:2000,'aria-label':'Exact quoted evidence'}),sources=el('textarea',{rows:2,maxlength:4000,'aria-label':'Source URLs'});const draft=drafts[claim.id];text.value=draft?draft.text:String(claim.text||'');quote.value=draft?draft.quote:String(claim.quotedEvidence||'');sources.value=draft?draft.sources:(Array.isArray(claim.sourceURLs)?claim.sourceURLs:[]).join('\n');for(const [name,input]of [['text',text],['quote',quote],['sources',sources]]){input.dataset.editKey=claim.id+':'+name;input.oninput=()=>{drafts[claim.id]={text:text.value,quote:quote.value,sources:sources.value}}}details.open=!!draft||opened.has(claim.id);summary.onclick=()=>{if(details.open)opened.delete(claim.id);else opened.add(claim.id)};form.append(field('Claim',text),field('Exact quote · paste only what the source says',quote),field('Source URLs · one per line',sources),el('p',{className:'muted'},'Saving edits returns the claim to pending verification.'),button('Save evidence',()=>saveEvidence()));const saveEvidence=()=>{const raw=sources.value.split('\n').map(value=>value.trim()).filter(Boolean),urls=raw.map(safeSourceURL);if(!text.value.trim()){notice.textContent='The claim needs text.';return}if(raw.length>5||urls.some(url=>!url)){notice.textContent='Use up to five valid http or https source URLs.';return}const savedDraft=drafts[claim.id];delete drafts[claim.id];if(!update('claim',claim.id,{text:text.value.trim(),quotedEvidence:quote.value.trim(),sourceURLs:urls,status:'pending',verifiedBy:null,verifiedAt:null})&&savedDraft)drafts[claim.id]=savedDraft};details.append(summary,form);panel.append(details,button('Delete claim',()=>commit({['claim:'+claim.id]:null}),'danger'));claims.append(panel)}if(!items.length)claims.append(empty('Add a claim, then attach the evidence you can inspect.'));restoreFocus(claims,focus)};
const addClaim=()=>{const input=document.getElementById('new-claim');if(!input.value.trim())return;if(records(state(),'claim').length>=20){notice.textContent='Keep up to 20 claims in this debate desk.';return}if(update('claim',id(),{text:input.value.trim(),side:document.getElementById('new-side').value,quotedEvidence:'',sourceURLs:[],status:'pending',at:Date.now(),createdBy:actor()}))input.value=''};
document.getElementById('add-button').onclick=addClaim;
window.addEventListener('present:state',render);render();
`);
