import { useEffect, useRef, useState } from 'react';
import { type Editor, type TLShapeId } from 'tldraw';
import { Canvas } from '../canvas';
import { useRoom } from '../room-client';
import './playbook.css';
type Phase={t:number;name:string;text:string};
type Replay={roomId:string;time:number;playing:boolean;speed:number;trails:boolean;frame:number;commitMs:number;duration:number;focusId:string;origin:{x:number;y:number};phase:Phase;phases:Phase[];error:string;decision?:{choice:string;modelMs:number}};
const roomId='dfbd64fbe874039f400b2cffeee953bf';
export function Playbook(){
 const room=useRoom(roomId,'Tactics studio');const[state,setState]=useState<Replay>();const[error,setError]=useState('');const[text,setText]=useState('');const[busy,setBusy]=useState(false);const[decision,setDecision]=useState('');const mounted=useRef(false);
 const fit=(editor:Editor=room.editor!)=>{if(!editor)return;const b=editor.getViewportScreenBounds();const z=Math.min((b.w-140)/1100,(b.h-80)/760);editor.setCamera({x:(b.w/z-1050)/2-10000,y:40/z-1000,z});};
 const command=async(input:Record<string,unknown>)=>{setBusy(true);setError('');try{const response=await fetch('/api/playbook',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const next=await response.json();if(!response.ok)throw new Error(next.error);setState(next);if(next.decision)setDecision(`Jev · ${next.decision.modelMs} ms · ${next.decision.choice}`);if(input.action==='prepare')fit();}catch(e){setError(e instanceof Error?e.message:'Could not update replay');}finally{setBusy(false);}};
 useEffect(()=>{let cancelled=false;const read=async()=>{try{const r=await fetch('/api/playbook');const next=await r.json();if(!cancelled)setState(next);}catch{}};void read();const id=setInterval(read,250);return()=>{cancelled=true;clearInterval(id)};},[]);
 useEffect(()=>{const editor=room.editor;if(!editor)return;const id=setTimeout(()=>fit(editor),500);const resize=()=>fit(editor);window.addEventListener('resize',resize);return()=>{clearTimeout(id);window.removeEventListener('resize',resize)};},[room.editor]);
 return <div className="playbook"><header className="pb-header"><a href="/" className="pb-brand">● present <span>/ playbook</span></a><span className="pb-live">● Native canvas · {room.connected?'connected':'connecting'}</span></header>
 <div className="pb-stage"><Canvas sync={room.sync} roomId={roomId} selfId={room.selfId} act={room.act} onMount={e=>{room.setEditor(e);if(!mounted.current){mounted.current=true;}}} onError={setError}/></div>
 <aside className="pb-sidebar"><div className="pb-kicker">MEXICO 1970 · THE FINAL</div><h1>The beautiful<br/><em>last pass.</em></h1><div className="pb-score"><span><i className="brazil"/>BRA</span><strong>{state?.time===30?'4':'3'} <small>—</small> 1</strong><span>ITA<i className="italy"/></span></div><p className="pb-sub">Carlos Alberto, 86′<br/>Brazil vs Italy · 21 June 1970</p>
 <button className="pb-build" disabled={busy} onClick={()=>command({action:'prepare'})}>Draw the pitch & players</button>
 <div className="pb-story"><span>{String((state?.phases.findIndex(p=>p.name===state.phase?.name)??0)+1).padStart(2,'0')} / 08</span><h2>{state?.phase?.name??'A team goal, made visible.'}</h2><p>{state?.phase?.text??'Draw an editable pitch. Then watch the ball and all 22 players move.'}</p></div>
 <div className="pb-beats">{state?.phases.map(p=><button key={p.t} className={state.phase?.t===p.t?'active':''} onClick={()=>command({action:'seek',time:p.t})}><span>{p.t.toFixed(0).padStart(2,'0')}</span>{p.name}</button>)}</div>
 <div className="pb-legend"><span><i className="brazil"/>Brazil · shirt numbers</span><span><i className="italy"/>Italy · schematic IDs</span><span>—→ Pass / shot &nbsp; ···→ Run</span></div>
 <p className="pb-disclaimer">An illustrative reconstruction. All 22 positions and the playback timing are approximate, not tracking data. <a href="https://inside.fifa.com/tournaments/mens/worldcup/1970mexico/news/brazil-s-history-making-hurricane-2865951" target="_blank" rel="noreferrer">The real goal ↗</a></p></aside>
 <footer className="pb-controls"><div className="pb-transport"><button aria-label="Rewind" onClick={()=>command({action:'rewind'})}>↶</button><button className="pb-play" aria-label={state?.playing?'Pause replay':'Play replay'} onClick={()=>command({action:state?.playing?'pause':'play'})}>{state?.playing?'Ⅱ':'▶'}</button><input aria-label="Replay position" type="range" min="0" max="30" step=".2" value={state?.time??0} onChange={e=>command({action:'seek',time:Number(e.target.value)})}/><span>{(state?.time??0).toFixed(1)} / 30</span><select aria-label="Replay speed" value={state?.speed??1} onChange={e=>command({action:'speed',speed:Number(e.target.value)})}><option value=".5">½×</option><option value="1">1×</option><option value="2">2×</option></select><button aria-pressed={state?.trails} onClick={()=>command({action:'trails',show:!state?.trails})}>Trails</button><button onClick={()=>fit()}>Fit</button></div>
 <form onSubmit={e=>{e.preventDefault();if(text.trim()){void command({action:'ask',text});setText('')}}}><span className="pb-spark">✧</span><input aria-label="Direct the replay" value={text} onChange={e=>setText(e.target.value)} placeholder="Try ‘rewind to Pelé’s pass’ or ‘play it slower’"/><button disabled={busy||!text.trim()} type="submit">↗</button><span className="pb-decision">{busy?'Listening…':decision||'Jev directs · native shapes move'}</span></form><div role="status" className="pb-error">{error||state?.error||room.error}</div></footer>
 </div>;
}
