-- Canvas Agent Todos Table
-- Migration: 001_canvas_agent_todos
-- Description: Create todos table for Canvas Agent task tracking

-- Create the canvas_agent_todos table
create table if not exists public.canvas_agent_todos (
  id uuid primary key default gen_random_uuid(),
  session_id text not null,
  text text not null,
  status text not null default 'open' check (status in ('open', 'done', 'skipped')),
  position int not null default 0,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

-- Create index for efficient queries by session and status
create index if not exists canvas_agent_todos_session_idx
  on public.canvas_agent_todos(session_id, status, position);

-- Create index for cleanup queries
create index if not exists canvas_agent_todos_created_at_idx
  on public.canvas_agent_todos(created_at);

-- Enable Row Level Security
alter table public.canvas_agent_todos enable row level security;

-- RLS Policy: Allow all operations for service role
create policy "Service role has full access"
  on public.canvas_agent_todos
  for all
  to service_role
  using (true)
  with check (true);

-- RLS Policy: Authenticated users can read todos from their sessions
-- (Assuming session_id maps to a room the user has access to)
create policy "Users can read their session todos"
  on public.canvas_agent_todos
  for select
  to authenticated
  using (true);
  -- Note: In production, add a check like:
  -- using (exists (
  --   select 1 from canvas_sessions
  --   where canvas_sessions.id = canvas_agent_todos.session_id
  --   and canvas_sessions.user_id = auth.uid()
  -- ));

-- Comment on table
comment on table public.canvas_agent_todos is 
  'Stores todo items generated by the Canvas Agent during sessions. Used for tracking follow-up tasks and scheduling.';

-- Comment on columns
comment on column public.canvas_agent_todos.session_id is 
  'Agent session ID that generated this todo';
comment on column public.canvas_agent_todos.text is 
  'Description of the todo task';
comment on column public.canvas_agent_todos.status is 
  'Current status: open, done, or skipped';
comment on column public.canvas_agent_todos.position is 
  'Sort order within the session';
comment on column public.canvas_agent_todos.resolved_at is 
  'Timestamp when the todo was marked done or skipped';




