-- 003_canvas_session_transcripts.sql
-- Append-only transcript storage for canvas sessions.
-- Motivation: avoid PATCHing a growing JSON blob (413s, row-lock contention, statement timeouts).

begin;

create table if not exists public.canvas_session_transcripts (
  id uuid primary key default gen_random_uuid(),
  -- Stable per-transcript id generated by the publisher (data-channel event_id).
  event_id text not null,
  session_id uuid not null references public.canvas_sessions (id) on delete cascade,
  room_name text not null,
  participant_id text not null,
  participant_name text null,
  text text not null,
  ts bigint not null,
  manual boolean not null default false,
  created_at timestamptz not null default now()
);

-- Idempotency / dedupe: multiple clients may attempt to persist the same transcript line.
create unique index if not exists canvas_session_transcripts_event_id_key
  on public.canvas_session_transcripts (event_id);

create index if not exists canvas_session_transcripts_session_ts_idx
  on public.canvas_session_transcripts (session_id, ts desc);

create index if not exists canvas_session_transcripts_room_ts_idx
  on public.canvas_session_transcripts (room_name, ts desc);

alter table public.canvas_session_transcripts enable row level security;

-- NOTE: This is intentionally permissive for an unreleased product.
-- Anonymous Supabase sign-in uses role "authenticated", so demo-mode users are covered.
do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'canvas_session_transcripts'
      and policyname = 'canvas_session_transcripts_select_authenticated'
  ) then
    create policy canvas_session_transcripts_select_authenticated
      on public.canvas_session_transcripts
      for select
      to authenticated
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'canvas_session_transcripts'
      and policyname = 'canvas_session_transcripts_insert_authenticated'
  ) then
    create policy canvas_session_transcripts_insert_authenticated
      on public.canvas_session_transcripts
      for insert
      to authenticated
      with check (true);
  end if;
end $$;

commit;

