# config/tasks.yaml
context_task:
  description: >
    Provide relevant context and background information for the statement "{{statement}}".
    Include sources and relevant facts that would help with verification.
  expected_output: >
    A comprehensive context report with relevant background information and sources.
  agent: context_provider

fact_check_task:
  description: >
    Analyze and fact-check the following statement: "{{statement}}".
    Verify its accuracy using reliable sources and provide a detailed explanation.
  expected_output: >
    A detailed fact-check report including verification status (true, false, partly true, etc.),
    evidence, sources, and explanation.
  agent: fact_checker

youtube_analysis_task:
  description: >
    I need you to analyze the YouTube video with the URL: "{{video_url}}"
    
    Specifically, search for mentions of these topics in the transcript: {{topics}}
    
    To accomplish this task, use the YouTube Transcript Analyzer tool with the following format:
    
    Action: YouTube Transcript Analyzer
    Action Input: {"video_url": "{{video_url}}", "topics": {{topics}}}
    
    After you get the results, provide a comprehensive analysis that includes:
    1. Summary of the video (title, channel, etc.)
    2. For each topic, show the number of times it was mentioned
    3. For each mention, provide the timestamp, the text containing the mention, and a direct link
    4. Highlight any patterns or interesting findings
    
    Be thorough and precise in your analysis.
  expected_output: >
    A detailed analysis of the YouTube video transcript, including:
    1. Video details (title, channel, etc.)
    2. Count of mentions for each requested topic
    3. List of all mentions with timestamps and text
    4. Direct links to jump to those timestamps in the video
    5. Analysis of patterns or notable findings
  agent: youtube_analyzer

profile_research_task:
  description: >
    I need you to research and create a comprehensive profile for the following query: "{{query}}"
    
    Use the Perplexity Deep Research tool with the following format:
    
    Action: Perplexity Deep Research
    Action Input: {"query": "{{query}}", "mode": "{{mode}}"}
    
    For mode, use "concise" for a quick overview or "detailed" for an in-depth analysis. The default is "concise".
    
    After you get the results, provide a comprehensive profile that includes:
    1. Main facts and information about the subject
    2. Background and context
    3. Notable achievements or contributions
    4. Any relevant connections or relationships
    5. Sources used for the research
    
    Be thorough but avoid including speculation or unverified information. Cite your sources appropriately.
  expected_output: >
    A detailed profile report including factual information about the subject, properly organized sections covering 
    background, achievements, and connections. All information should be properly sourced and presented in a 
    professional, unbiased manner.
  agent: profile_researcher