export const presetStyle = `<style>
body{padding:18px 22px 22px}button{border:0;border-radius:8px;padding:10px 16px;background:#d9ef9c;color:#28342a}button.quiet{background:#f0f2e9;color:#64705c}label,.muted{font-size:12px;color:#7b8675}input[type=range]{width:100%;accent-color:#91ad67}input,textarea{color:#28342a;background:transparent;border:0;outline:none}textarea{resize:none}h2,p{margin:0}.row{display:flex;align-items:center;gap:9px}.spread{justify-content:space-between}.stack{display:flex;flex-direction:column;gap:18px}.serif{font-family:Georgia,serif}
</style>`;

export const diceHtml = `${presetStyle}
<style>.dice{display:grid;place-items:center;height:124px;font-size:84px;font-weight:350;line-height:1}.rolls{text-align:center;margin-bottom:20px}button{width:100%}.dice.rolling{animation:tumble .3s ease}@keyframes tumble{50%{transform:rotate(12deg) scale(.84)}}@media(prefers-reduced-motion:reduce){.dice.rolling{animation:none}}</style>
<div class="dice" id="value">—</div><p class="muted rolls" id="rolls">A little chance.</p><button id="roll">Roll the dice</button>
<script>(()=>{const value=document.getElementById('value'),rolls=document.getElementById('rolls');function render(){const s=present.getState();value.textContent=s.value||'—';rolls.textContent=s.rolls?'Roll '+s.rolls:'A little chance.'}document.getElementById('roll').onclick=()=>{present.setState({value:Math.floor(Math.random()*6)+1});present.increment('rolls');value.classList.remove('rolling');void value.offsetWidth;value.classList.add('rolling')};window.addEventListener('present:state',render);render()})()</script>`;

export const pollHtml = `${presetStyle}
<style>h2{font-weight:400;font-size:24px;line-height:1.2;margin:4px 0 20px}.option{display:flex;justify-content:space-between;width:100%;margin-bottom:8px;text-align:left;background:#f0f2e9}.option strong{font-variant-numeric:tabular-nums;font-weight:500}.option:hover{background:#e6edda}.option[aria-pressed=true]{background:#d9ef9c}.total{margin-top:16px}.question{font:inherit;width:100%;padding:0}</style>
<h2 class="serif"><input class="question" id="question" aria-label="Poll question"></h2><div id="options"></div><p class="muted total" id="total"></p>
<script>(()=>{const labels=['Explore a little','Make something','Take a breath'],options=document.getElementById('options'),question=document.getElementById('question'),voteKey='vote:'+present.participantId;labels.forEach((label,index)=>{const button=document.createElement('button');button.className='option';const name=document.createElement('span'),count=document.createElement('strong');name.textContent=label;button.append(name,count);button.onclick=()=>{if(present.participantId)present.setState({[voteKey]:index})};options.append(button)});question.onchange=()=>present.setState({question:question.value});function render(){const s=present.getState(),counts=[0,0,0];for(const [key,vote] of Object.entries(s))if(key.startsWith('vote:')&&Number.isInteger(vote)&&vote>=0&&vote<labels.length)counts[vote]++;if(document.activeElement!==question)question.value=s.question||'Where do we go next?';[...options.children].forEach((button,index)=>{button.lastChild.textContent=counts[index];button.setAttribute('aria-pressed',String(s[voteKey]===index))});const total=counts.reduce((sum,n)=>sum+n,0),voted=Object.hasOwn(s,voteKey);document.getElementById('total').textContent=total?total+(total===1?' vote':' votes')+(voted?' · your choice is saved':' · add yours'):'Tap to add your vote.'}window.addEventListener('present:state',render);render()})()</script>`;

export const teleprompterHtml = `${presetStyle}
<style>html,body{height:100%;overflow:hidden}body{display:flex;flex-direction:column;gap:16px}.stage{flex:1;min-height:0;overflow:hidden;scrollbar-width:none}.script{white-space:pre-wrap;font-size:27px;line-height:1.6;padding:35px 0 130px}.editor{display:none;width:100%;height:100%;font-size:19px;line-height:1.5}.controls{flex-shrink:0}.controls input{width:70px;margin-left:auto}.controls label{margin-left:auto}.editing .script{display:none}.editing .editor{display:block}</style>
<div class="stage" id="stage"><div class="script serif" id="script"></div><textarea class="editor" id="editor" aria-label="Teleprompter script"></textarea></div><div class="row controls"><button id="play">Begin</button><button class="quiet" id="edit">Edit</button><label for="speed">Pace</label><input id="speed" aria-label="Scroll pace" type="range" min="10" max="70" value="24"></div>
<script>(()=>{const stage=document.getElementById('stage'),script=document.getElementById('script'),editor=document.getElementById('editor'),play=document.getElementById('play'),edit=document.getElementById('edit'),speed=document.getElementById('speed');let editing=false;const offset=s=>(Number(s.offset)||0)+(s.playing&&s.startedAt?(Date.now()-s.startedAt)/1000*(Number(s.speed)||24):0);function render(){const s=present.getState();script.textContent=s.text||'';play.textContent=s.playing?'Pause':'Begin';speed.value=s.speed||24;if(!editing)editor.value=s.text||''}play.onclick=()=>{if(editing)return;const s=present.getState();present.setState(s.playing?{playing:false,offset:offset(s),startedAt:null}:{playing:true,startedAt:Date.now(),offset:stage.scrollTop>=stage.scrollHeight-stage.clientHeight-2?0:Number(s.offset)||0})};edit.onclick=()=>{const s=present.getState();if(editing){present.setState({text:editor.value,offset:0,playing:false,startedAt:null})}else{present.setState({playing:false,offset:0,startedAt:null});editor.value=s.text||''}editing=!editing;stage.classList.toggle('editing',editing);edit.textContent=editing?'Save':'Edit';play.disabled=editing;if(editing)editor.focus()};speed.oninput=()=>{const s=present.getState();present.setState({speed:Number(speed.value),offset:offset(s),startedAt:s.playing?Date.now():null})};window.addEventListener('present:state',render);setInterval(()=>{if(!editing)stage.scrollTop=offset(present.getState())},40);render()})()</script>`;

export const synthHtml = `${presetStyle}
<style>.tone{font-size:52px;font-weight:350;letter-spacing:-2px;margin:2px 0 0}.tone small{font-size:14px;letter-spacing:0;color:#7b8675}svg{height:55px;width:100%;margin:6px 0;overflow:visible}.waveforms button{padding:6px 12px;font-size:12px;background:#f0f2e9}.waveforms button.active{background:#d9ef9c}.foot{margin-top:12px}</style>
<div class="stack"><div class="tone"><span id="frequency">220</span> <small>Hz</small></div><svg viewBox="0 0 300 50" aria-hidden="true"><path id="wave" fill="none" stroke="#91ad67" stroke-width="2"/></svg><input type="range" id="pitch" aria-label="Pitch" min="80" max="880" value="220"><div class="row spread"><button id="sound">Sound on</button><div class="row waveforms"><button id="sine">Sine</button><button id="triangle">Triangle</button></div></div></div><p class="muted foot">A shared tone. Sound on your device.</p>
<script>(()=>{let context,oscillator,gain,playing=false;const sound=document.getElementById('sound'),pitch=document.getElementById('pitch');function render(){const s=present.getState(),frequency=Math.max(80,Math.min(880,Number(s.frequency)||220)),waveform=s.waveform==='triangle'?'triangle':'sine';document.getElementById('frequency').textContent=Math.round(frequency);pitch.value=frequency;['sine','triangle'].forEach(w=>document.getElementById(w).classList.toggle('active',w===waveform));if(oscillator){oscillator.frequency.setTargetAtTime(frequency,context.currentTime,.03);oscillator.type=waveform}let d='';for(let x=0;x<=300;x+=2){const phase=x/300*Math.PI*2*(frequency/110),y=25+(waveform==='sine'?Math.sin(phase):2/Math.PI*Math.asin(Math.sin(phase)))*19;d+=(x?'L':'M')+x+' '+y}document.getElementById('wave').setAttribute('d',d)}sound.onclick=async()=>{if(!context){context=new AudioContext();oscillator=context.createOscillator();gain=context.createGain();gain.gain.value=0;oscillator.connect(gain).connect(context.destination);oscillator.start()}await context.resume();playing=!playing;gain.gain.setTargetAtTime(playing?.08:0,context.currentTime,.04);sound.textContent=playing?'Sound off':'Sound on';render()};pitch.oninput=()=>present.setState({frequency:Number(pitch.value)});['sine','triangle'].forEach(w=>document.getElementById(w).onclick=()=>present.setState({waveform:w}));window.addEventListener('present:state',render);window.addEventListener('pagehide',()=>context?.close());render()})()</script>`;
